# Generated by Django 6.0.1 on 2026-06-04 12:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPlanningRequirementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_sales_planning_requirement', 'Can view Sales Planning vs Requirement dashboard'), ('can_refresh_sales_planning_requirement', 'Can refresh Sales Planning vs Requirement data')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalesPlanningRequirementRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('source_schema', models.CharField(max_length=128)),
                ('procedure_name', models.CharField(default='SALES PLANNING VS REQUIREMENT_OLD', max_length=255)),
                ('forecast_id', models.IntegerField(blank=True, null=True)),
                ('forecast_name', models.CharField(blank=True, max_length=255)),
                ('forecast_start_date', models.DateField(blank=True, null=True)),
                ('forecast_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('command', 'Command')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rows_loaded', models.PositiveIntegerField(default=0)),
                ('column_metadata', models.JSONField(blank=True, default=list)),
                ('procedure_parameters', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_planning_requirement_refresh_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesPlanningRequirementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=50)),
                ('source_schema', models.CharField(max_length=128)),
                ('forecast_id', models.IntegerField(blank=True, null=True)),
                ('forecast_name', models.CharField(blank=True, max_length=255)),
                ('forecast_start_date', models.DateField(blank=True, null=True)),
                ('forecast_end_date', models.DateField(blank=True, null=True)),
                ('planning_month', models.CharField(blank=True, max_length=255)),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=500)),
                ('planned_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('base_required_qty', models.DecimalField(blank=True, decimal_places=6, help_text='Forecast/BOM requirement before final stock adjustment where available.', max_digits=24, null=True)),
                ('min_stock', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('stock_in_hand', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('required_qty', models.DecimalField(decimal_places=6, help_text='Final quantity required after min stock and current stock adjustments.', max_digits=24)),
                ('open_po_qty', models.DecimalField(decimal_places=6, default=0, max_digits=24)),
                ('net_shortage_qty', models.DecimalField(decimal_places=6, default=0, help_text='Required quantity still not covered by open purchase orders.', max_digits=24)),
                ('report_execution_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', to='sales_planning_requirement.salesplanningrequirementrefreshrun')),
            ],
            options={
                'ordering': ['item_code'],
            },
        ),
        migrations.AddIndex(
            model_name='salesplanningrequirementrefreshrun',
            index=models.Index(fields=['company_code', 'status'], name='sales_plann_company_9d6f37_idx'),
        ),
        migrations.AddIndex(
            model_name='salesplanningrequirementrefreshrun',
            index=models.Index(fields=['company_code', '-started_at'], name='sales_plann_company_ac00d3_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesplanningrequirementrefreshrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('company_code',), name='uniq_running_sales_planning_refresh'),
        ),
        migrations.AddIndex(
            model_name='salesplanningrequirementrow',
            index=models.Index(fields=['company_code', 'forecast_id'], name='sales_plann_company_a0c07c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesplanningrequirementrow',
            index=models.Index(fields=['company_code', 'item_code'], name='sales_plann_company_c39064_idx'),
        ),
        migrations.AddIndex(
            model_name='salesplanningrequirementrow',
            index=models.Index(fields=['company_code', '-net_shortage_qty'], name='sales_plann_company_497b80_idx'),
        ),
        migrations.AddIndex(
            model_name='salesplanningrequirementrow',
            index=models.Index(fields=['loaded_at'], name='sales_plann_loaded__2291a4_idx'),
        ),
    ]
