# Generated by Django 6.0.1 on 2026-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_planning_requirement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesplanningrequirementrefreshrun',
            name='procedure_name',
            field=models.CharField(default='SALES PLANNING VS REQUIREMENT_WEEKLY', max_length=255),
        ),
    ]
