# Generated by Django 6.0.1 on 2026-05-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0016_update_line_config_add_name_remove_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineskuconfig',
            name='electricity_cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preset electricity cost per hour', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lineskuconfig',
            name='labour_cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preset labour cost per hour', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='electricity_cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preset electricity cost per hour copied from the selected line config', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='labour_cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preset labour cost per hour copied from the selected line config', max_digits=12, null=True),
        ),
    ]
