# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0017_lineskuconfig_electricity_cost_per_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineskuconfig',
            old_name='electricity_cost_per_hour',
            new_name='electricity_cost_per_unit',
        ),
        migrations.RenameField(
            model_name='productionrun',
            old_name='electricity_cost_per_hour',
            new_name='electricity_cost_per_unit',
        ),
        migrations.AlterField(
            model_name='lineskuconfig',
            name='electricity_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preset electricity cost per unit', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='electricity_cost_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Preset electricity cost per unit copied from the selected line config', max_digits=12, null=True),
        ),
    ]
