# Generated by Codex on 2026-05-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0017_simplify_line_clearance'),
        ('production_execution', '0018_rename_electricity_cost_per_unit'),
    ]

    operations = []
