# Generated by Codex on 2026-05-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0018_enforce_lineclearance_schema'),
        ('production_execution', '0021_repair_lineclearance_all_checks_passed'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE production_execution_lineclearance
            ADD COLUMN IF NOT EXISTS all_checks_passed boolean NOT NULL DEFAULT false;

            ALTER TABLE production_execution_lineclearance
            DROP COLUMN IF EXISTS production_incharge_sign;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
