# Generated by Django 6.0.1 on 2026-05-11 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_execution', '0022_merge_material_consumption_line_clearance_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machinebreakdown',
            options={'ordering': ['start_time'], 'verbose_name': 'Breakdown', 'verbose_name_plural': 'Breakdowns'},
        ),
        migrations.AlterField(
            model_name='machinebreakdown',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdowns', to='production_execution.machine'),
        ),
    ]
