# Generated by Django 6.0.3 on 2026-05-08 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0004_rename_dispatch_pl_company_d4f18f_idx_dispatch_pl_company_4e52c8_idx'),
        ('grpo', '0011_populate_po_receipts_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGRPOPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(help_text='SAP transporter/vendor Business Partner code', max_length=50)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=150)),
                ('sap_doc_entry', models.IntegerField(blank=True, help_text='SAP DocEntry', null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, help_text='SAP DocNum', null=True)),
                ('sap_doc_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed'), ('PARTIALLY_POSTED', 'Partially Posted')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_grpo_postings', to='dispatch_plans.dispatchplan')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_grpo_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGRPOLinePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_code', models.CharField(blank=True, default='', max_length=50)),
                ('gl_account', models.CharField(blank=True, default='', max_length=50)),
                ('service_grpo_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='grpo.servicegrpoposting')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGRPOAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service_grpo_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('sap_attachment_status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded to SAP'), ('LINKED', 'Linked to GRPO Document'), ('FAILED', 'Upload Failed')], default='PENDING', max_length=20)),
                ('sap_absolute_entry', models.IntegerField(blank=True, null=True)),
                ('sap_error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_grpo_attachments', to=settings.AUTH_USER_MODEL)),
                ('service_grpo_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grpo.servicegrpoposting')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicegrpoposting',
            index=models.Index(fields=['dispatch_plan', 'status'], name='grpo_servic_dispatc_6f1d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegrpoposting',
            index=models.Index(fields=['vendor_code', 'status'], name='grpo_servic_vendor__24aa13_idx'),
        ),
    ]
