# Generated by Django 6.0.3 on 2026-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grpo', '0012_servicegrpoposting_servicegrpolineposting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='location_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='product_variety',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='project_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='sac_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='sac_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='total_litres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='servicegrpolineposting',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='budget_delivery_point',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='effective_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='location_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='place_of_supply',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='product_variety',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='sac_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='sac_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicegrpoposting',
            name='total_litres',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
