# Generated by Django 6.0.1 on 2026-05-11 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_production_qc_approval_permission(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    content_type, _ = ContentType.objects.get_or_create(
        app_label='quality_control',
        model='productionqcsession',
    )
    permission, _ = Permission.objects.get_or_create(
        content_type=content_type,
        codename='can_approve_production_qc',
        defaults={'name': 'Can approve production QC session'},
    )

    for group_name in ('QC Manager', 'qc_manager'):
        group, _ = Group.objects.get_or_create(name=group_name)
        group.permissions.add(permission)


def remove_production_qc_approval_permission_from_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    try:
        permission = Permission.objects.get(
            content_type__app_label='quality_control',
            codename='can_approve_production_qc',
        )
    except Permission.DoesNotExist:
        return

    for group_name in ('QC Manager', 'qc_manager'):
        try:
            group = Group.objects.get(name=group_name)
        except Group.DoesNotExist:
            continue
        group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('quality_control', '0021_alter_productionqcsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionqcsession',
            options={'ordering': ['session_number'], 'permissions': [('can_view_production_qc', 'Can view production QC'), ('can_create_production_qc', 'Can create production QC session'), ('can_submit_production_qc', 'Can submit production QC session'), ('can_approve_production_qc', 'Can approve production QC session')]},
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='approval_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_sessions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_qc_sessions_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionqcsession',
            name='rejection_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productionqcsession',
            name='workflow_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15),
        ),
        migrations.RunPython(
            grant_production_qc_approval_permission,
            remove_production_qc_approval_permission_from_groups,
        ),
    ]
