# Generated by Django 6.0.3 on 2026-05-11 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0022_alter_productionqcsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionqcsession',
            name='material_type',
            field=models.ForeignKey(blank=True, help_text='Product/material type defining which QC parameters to check', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_qc_sessions', to='quality_control.materialtype'),
        ),
    ]
