# Generated by Codex on 2026-05-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0022_factory_head_decision"),
        ("quality_control", "0023_alter_productionqcsession_material_type"),
    ]

    operations = []
