# Generated by Django 6.0.1 on 2026-06-02 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_view_maintenance_module', 'Can view Maintenance module'), ('can_view_maintenance_dashboard', 'Can view Maintenance dashboard'), ('can_manage_maintenance_settings', 'Can manage Maintenance settings'), ('can_view_work_order', 'Can view Maintenance work orders'), ('can_manage_work_order', 'Can manage Maintenance work orders'), ('can_create_work_order', 'Can create Maintenance work orders'), ('can_assign_work_order', 'Can assign Maintenance work orders'), ('can_start_work_order', 'Can start Maintenance work orders'), ('can_complete_work_order', 'Can complete Maintenance work orders'), ('can_approve_work_order', 'Can approve Maintenance work order closure'), ('can_close_work_order', 'Can close Maintenance work orders'), ('can_view_pm', 'Can view preventive maintenance'), ('can_manage_pm', 'Can manage preventive maintenance'), ('can_view_spare', 'Can view Maintenance spares'), ('can_manage_spare', 'Can manage Maintenance spares'), ('can_view_vendor', 'Can view Maintenance vendors'), ('can_manage_vendor', 'Can manage Maintenance vendors'), ('can_view_maintenance_reports', 'Can view Maintenance reports')]},
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_order_no', models.CharField(max_length=80)),
                ('work_type', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('BREAKDOWN', 'Breakdown'), ('GENERAL', 'General Maintenance'), ('PREVENTIVE', 'Preventive Maintenance'), ('INSPECTION', 'Inspection'), ('CALIBRATION', 'Calibration'), ('AMC_VENDOR', 'AMC / Vendor Visit'), ('PROJECT', 'Project / Improvement')], default='COMPLAINT', max_length=30)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_SPARE', 'Waiting Spare'), ('WAITING_VENDOR', 'Waiting Vendor'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('CLOSED', 'Closed')], default='OPEN', max_length=30)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('line', models.CharField(blank=True, default='', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('impact', models.CharField(choices=[('NO_IMPACT', 'No Production Impact'), ('DEGRADED', 'Reduced Performance'), ('STOPPAGE', 'Production Stoppage'), ('SAFETY_RISK', 'Safety Risk')], default='NO_IMPACT', max_length=30)),
                ('impact_notes', models.TextField(blank=True, default='')),
                ('downtime_reason', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('technician_remarks', models.TextField(blank=True, default='')),
                ('completion_remarks', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('preventive_action', models.TextField(blank=True, default='')),
                ('closure_remarks', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_assigned', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_closed', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_work_orders', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='maintenance.assetdepartment')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders_reported', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Work Order',
                'verbose_name_plural': 'Maintenance Work Orders',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'work_order_no')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before'), ('AFTER', 'After'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('photo', models.FileField(upload_to='maintenance/work-orders/photos/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('taken_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Work Order Photo',
                'verbose_name_plural': 'Maintenance Work Order Photos',
                'ordering': ['photo_type', '-taken_on', '-created_at'],
            },
        ),
    ]
