# Generated by Django 6.0.1 on 2026-06-02 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenancepermission_options_and_more'),
        ('production_execution', '0023_alter_machinebreakdown_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='production_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_assets', to='production_execution.machine'),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='production_breakdown',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_order', to='production_execution.machinebreakdown'),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='production_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_work_orders', to='production_execution.productionrun'),
        ),
    ]
