# Generated by Django 6.0.1 on 2026-06-03 06:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0003_asset_production_machine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Spare Category',
                'verbose_name_plural': 'Maintenance Spare Categories',
                'ordering': ['name'],
                'abstract': False,
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSpare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=100)),
                ('sap_item_code', models.CharField(blank=True, default='', max_length=100)),
                ('uom', models.CharField(default='NOS', max_length=30)),
                ('is_critical', models.BooleanField(default=False)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('reorder_level', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('storage_location', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spares', to='company.company')),
                ('compatible_assets', models.ManyToManyField(blank=True, related_name='compatible_spares', to='maintenance.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spares', to='maintenance.sparecategory')),
            ],
            options={
                'verbose_name': 'Maintenance Spare',
                'verbose_name_plural': 'Maintenance Spares',
                'ordering': ['part_number', 'name'],
                'unique_together': {('company', 'part_number')},
            },
        ),
        migrations.CreateModel(
            name='SpareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('ISSUED', 'Issued'), ('PARTIALLY_CONSUMED', 'Partially Consumed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('requested_qty', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('issued_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('consumed_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('returned_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('required_by', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('store_remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_requests', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_spare_requests', to=settings.AUTH_USER_MODEL)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='maintenance.maintenancespare')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_requests', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Spare Request',
                'verbose_name_plural': 'Maintenance Spare Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpareMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('movement_type', models.CharField(choices=[('ISSUE', 'Issue to Work Order'), ('CONSUME', 'Consume on Work Order'), ('RETURN', 'Return Unused Spare'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_movements', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_spare_movements', to=settings.AUTH_USER_MODEL)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='maintenance.maintenancespare')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_movements', to='maintenance.maintenanceworkorder')),
                ('spare_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='maintenance.sparerequest')),
            ],
            options={
                'verbose_name': 'Maintenance Spare Movement',
                'verbose_name_plural': 'Maintenance Spare Movements',
                'ordering': ['-created_at'],
            },
        ),
    ]
