# Generated by Django 6.0.1 on 2026-06-03 07:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('maintenance', '0004_sparecategory_maintenancespare_sparerequest_and_more'),
        ('maintenance_gatein', '0009_maintenancegateentry_updated_at'),
        ('person_gatein', '0007_entrylog_actual_entry_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparemovement',
            name='movement_type',
            field=models.CharField(choices=[('RECEIPT', 'Receipt from Gate'), ('ISSUE', 'Issue to Work Order'), ('CONSUME', 'Consume on Work Order'), ('RETURN', 'Return Unused Spare'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sparemovement',
            name='spare_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='maintenance.sparerequest'),
        ),
        migrations.AlterField(
            model_name='sparemovement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_movements', to='maintenance.maintenanceworkorder'),
        ),
        migrations.CreateModel(
            name='MaintenanceGateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qc_required', models.BooleanField(default=False)),
                ('qc_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAIVED', 'Waived')], default='NOT_REQUIRED', max_length=20)),
                ('grpo_reference', models.CharField(blank=True, default='', max_length=120)),
                ('grpo_doc_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('grpo_doc_num', models.CharField(blank=True, default='', max_length=50)),
                ('receipt_status', models.CharField(choices=[('NOT_RECEIVED', 'Not Received'), ('RECEIVED', 'Received'), ('BLOCKED', 'Blocked')], default='NOT_RECEIVED', max_length=20)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_links', to='maintenance.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_gate_links', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gate_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_link', to='maintenance_gatein.maintenancegateentry')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_gate_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('spare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_links', to='maintenance.maintenancespare')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_links', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Gate Link',
                'verbose_name_plural': 'Maintenance Gate Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSpareReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('qc_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAIVED', 'Waived')], default='NOT_REQUIRED', max_length=20)),
                ('grpo_reference', models.CharField(blank=True, default='', max_length=120)),
                ('grpo_doc_entry', models.PositiveIntegerField(blank=True, null=True)),
                ('grpo_doc_num', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_receipts', to='maintenance.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_spare_receipts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gate_link', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='spare_receipt', to='maintenance.maintenancegatelink')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_spare_receipts_received', to=settings.AUTH_USER_MODEL)),
                ('spare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_receipts', to='maintenance.maintenancespare')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_receipts', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Spare Receipt',
                'verbose_name_plural': 'Maintenance Spare Receipts',
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceVendorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor_code', models.CharField(blank=True, default='', max_length=80)),
                ('vendor_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('service_report_attachment', models.FileField(blank=True, null=True, upload_to='maintenance/vendor-visits/service-reports/')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_attachment', models.FileField(blank=True, null=True, upload_to='maintenance/vendor-visits/invoices/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_visits', to='maintenance.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_vendor_visits', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material_gate_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_visits', to='maintenance_gatein.maintenancegateentry')),
                ('person_gate_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_vendor_visits', to='person_gatein.entrylog')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_visits', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'verbose_name': 'Maintenance Vendor Visit',
                'verbose_name_plural': 'Maintenance Vendor Visits',
                'ordering': ['-planned_start', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancegatelink',
            index=models.Index(fields=['company', 'receipt_status'], name='maintenance_company_167000_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancegatelink',
            index=models.Index(fields=['company', 'qc_status'], name='maintenance_company_f267fb_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancegatelink',
            index=models.Index(fields=['asset'], name='maintenance_asset_i_3296f4_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancegatelink',
            index=models.Index(fields=['work_order'], name='maintenance_work_or_b72a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancegatelink',
            index=models.Index(fields=['spare'], name='maintenance_spare_i_524367_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevendorvisit',
            index=models.Index(fields=['company', 'status'], name='maintenance_company_5b6dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevendorvisit',
            index=models.Index(fields=['work_order'], name='maintenance_work_or_6351b5_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevendorvisit',
            index=models.Index(fields=['asset'], name='maintenance_asset_i_fb6530_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancevendorvisit',
            index=models.Index(fields=['vendor_code'], name='maintenance_vendor__123869_idx'),
        ),
    ]
