# Generated by Django 6.0.1 on 2026-05-08 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sap_invoice_doc_entry', models.IntegerField()),
                ('sap_invoice_doc_num', models.CharField(blank=True, default='', max_length=30)),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('BOOKED', 'Booked'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, default='', max_length=50)),
                ('transporter_name', models.CharField(blank=True, default='', max_length=150)),
                ('transporter_gstin', models.CharField(blank=True, default='', max_length=20)),
                ('contact_person', models.CharField(blank=True, default='', max_length=100)),
                ('mobile_no', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_no', models.CharField(blank=True, default='', max_length=30)),
                ('bilty_no', models.CharField(blank=True, default='', max_length=50)),
                ('bilty_date', models.DateField(blank=True, null=True)),
                ('freight', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_freight', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('kanta_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_plans', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'permissions': [('can_view_dispatch_plans', 'Can view Dispatch Plans dashboard'), ('can_edit_dispatch_plans', 'Can edit Dispatch Plans bookings')],
                'indexes': [models.Index(fields=['company', 'sap_invoice_doc_entry'], name='dispatch_pl_company_2ef308_idx'), models.Index(fields=['company', 'booking_status'], name='dispatch_pl_company_c789a0_idx'), models.Index(fields=['company', 'dispatch_date'], name='dispatch_pl_company_6952b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'sap_invoice_doc_entry'), name='unique_dispatch_plan_invoice_per_company')],
            },
        ),
    ]
