# Generated by Django 6.0.1 on 2026-05-08 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('dispatch_plans', '0001_initial'),
        ('driver_management', '0010_alter_vehicleentry_entry_type'),
        ('vehicle_management', '0006_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchplan',
            name='linked_vehicle_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_plans', to='driver_management.vehicleentry'),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_plans', to='vehicle_management.transporter'),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_plans', to='vehicle_management.vehicle'),
        ),
        migrations.AddIndex(
            model_name='dispatchplan',
            index=models.Index(fields=['company', 'vehicle'], name='dispatch_pl_company_b477e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchplan',
            index=models.Index(fields=['company', 'linked_vehicle_entry'], name='dispatch_pl_company_8fd192_idx'),
        ),
    ]
