# Generated by Django 6.0.1 on 2026-05-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0003_dispatchplan_driver_and_driver_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatchplan',
            new_name='dispatch_pl_company_4e52c8_idx',
            old_name='dispatch_pl_company_d4f18f_idx',
        ),
    ]
