# Generated by Django 6.0.3 on 2026-05-15 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('dispatch_plans', '0006_add_dispatch_vehicle_linking_permission'),
        ('grpo', '0012_servicegrpoposting_servicegrpolineposting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterAPInvoicePosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor_code', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=150)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('selected_grpo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('branch_id', models.IntegerField()),
                ('sap_doc_entry', models.IntegerField(blank=True, null=True)),
                ('sap_doc_num', models.IntegerField(blank=True, null=True)),
                ('sap_doc_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('POSTED', 'Posted to SAP'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transporter_ap_invoice_postings', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter_ap_invoice_postings', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view_open_bilties', 'Can view open dispatch bilties'), ('can_post_bilty_service_grpo', 'Can post bilty service GRPO'), ('can_view_transporter_ap_invoice', 'Can view transporter AP invoices'), ('can_post_transporter_ap_invoice', 'Can post transporter AP invoices')],
            },
        ),
        migrations.CreateModel(
            name='TransporterAPInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_entry', models.IntegerField()),
                ('base_line', models.IntegerField()),
                ('base_doc_num', models.IntegerField(blank=True, null=True)),
                ('bilty_no', models.CharField(blank=True, default='', max_length=50)),
                ('service_description', models.CharField(blank=True, default='', max_length=255)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax_code', models.CharField(blank=True, default='', max_length=50)),
                ('gl_account', models.CharField(blank=True, default='', max_length=50)),
                ('dispatch_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transporter_ap_invoice_lines', to='dispatch_plans.dispatchplan')),
                ('service_grpo_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transporter_ap_invoice_lines', to='grpo.servicegrpolineposting')),
                ('service_grpo_posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transporter_ap_invoice_lines', to='grpo.servicegrpoposting')),
                ('transporter_ap_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dispatch_plans.transporterapinvoiceposting')),
            ],
        ),
        migrations.CreateModel(
            name='TransporterAPInvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transporter_ap_invoice_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('sap_attachment_status', models.CharField(choices=[('PENDING', 'Pending Upload'), ('UPLOADED', 'Uploaded to SAP'), ('LINKED', 'Linked to SAP Document'), ('FAILED', 'Upload Failed')], default='PENDING', max_length=20)),
                ('sap_absolute_entry', models.IntegerField(blank=True, null=True)),
                ('sap_error_message', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter_ap_invoice_attachments', to=settings.AUTH_USER_MODEL)),
                ('transporter_ap_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dispatch_plans.transporterapinvoiceposting')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transporterapinvoiceposting',
            index=models.Index(fields=['company', 'vendor_code', 'invoice_number'], name='dispatch_pl_company_d5dc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='transporterapinvoiceposting',
            index=models.Index(fields=['company', 'status'], name='dispatch_pl_company_dc1430_idx'),
        ),
        migrations.AddIndex(
            model_name='transporterapinvoiceposting',
            index=models.Index(fields=['sap_doc_entry'], name='dispatch_pl_sap_doc_9ae580_idx'),
        ),
        migrations.AddIndex(
            model_name='transporterapinvoiceline',
            index=models.Index(fields=['base_entry', 'base_line'], name='dispatch_pl_base_en_5cdc23_idx'),
        ),
        migrations.AddIndex(
            model_name='transporterapinvoiceline',
            index=models.Index(fields=['dispatch_plan'], name='dispatch_pl_dispatc_e1c44a_idx'),
        ),
    ]
