# Generated by Django 6.0.3 on 2026-05-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_plans', '0007_transporterapinvoiceposting_transporterapinvoiceline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchplan',
            name='eway_bill',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='invoice_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='dispatchplan',
            name='place_of_supply',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
