# Generated by Django 6.0.1 on 2026-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0006_alter_vehicleentry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('DAILY_NEED', 'Daily Need / Canteen'), ('MAINTENANCE', 'Maintenance'), ('CONSTRUCTION', 'Construction'), ('EMPTY_VEHICLE', 'Empty Vehicle')], max_length=20),
        ),
    ]
