# Generated by Django 6.0.3 on 2026-05-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0007_alter_vehicleentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='entry_type',
            field=models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('DAILY_NEED', 'Daily Need / Canteen'), ('MAINTENANCE', 'Maintenance'), ('CONSTRUCTION', 'Construction'), ('EMPTY_VEHICLE', 'Empty Vehicle'), ('BST_IN', 'BST In')], max_length=20),
        ),
    ]
