# Generated by Codex on 2026-05-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0004_box_g_weight_box_n_weight'),
        ('company', '0003_alter_usercompany_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_type', models.CharField(max_length=20)),
                ('date_str', models.CharField(max_length=8)),
                ('line_key', models.CharField(max_length=50)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_sequences', to='company.company')),
            ],
            options={
                'verbose_name': 'Barcode Sequence',
                'verbose_name_plural': 'Barcode Sequences',
                'ordering': ['sequence_type', 'date_str', 'line_key'],
                'unique_together': {('company', 'sequence_type', 'date_str', 'line_key')},
            },
        ),
    ]
