# Generated by Django 6.0.1 on 2026-05-23 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0006_pallet_max_box_count'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=80)),
                ('sap_system_type', models.CharField(choices=[('S4HANA', 'S/4HANA'), ('ECC', 'ECC'), ('BUSINESS_ONE', 'SAP Business One')], default='BUSINESS_ONE', max_length=30)),
                ('sap_object_type', models.CharField(choices=[('BILLING_DOCUMENT', 'Billing Document'), ('AR_INVOICE', 'A/R Invoice'), ('OUTBOUND_DELIVERY', 'Outbound Delivery')], default='AR_INVOICE', max_length=40)),
                ('sap_doc_entry', models.CharField(blank=True, default='', max_length=80)),
                ('sap_doc_num', models.CharField(blank=True, default='', max_length=80)),
                ('reference_delivery_number', models.CharField(blank=True, default='', max_length=80)),
                ('customer_code', models.CharField(blank=True, default='', max_length=80)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('ship_to_code', models.CharField(blank=True, default='', max_length=80)),
                ('ship_to_name', models.CharField(blank=True, default='', max_length=255)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('SCANNING_COMPLETE', 'Scanning Complete'), ('DISPATCHED', 'Dispatched'), ('SAP_UPDATE_PENDING', 'SAP Update Pending'), ('SAP_UPDATE_FAILED', 'SAP Update Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('sap_dispatch_status', models.CharField(blank=True, default='', max_length=80)),
                ('sap_update_status', models.CharField(choices=[('NOT_CONFIGURED', 'Not Configured'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='NOT_CONFIGURED', max_length=30)),
                ('sap_update_error', models.TextField(blank=True, default='')),
                ('sap_snapshot', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_dispatches_cancelled', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_dispatch_sessions', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_dispatches_created', to=settings.AUTH_USER_MODEL)),
                ('dispatched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_dispatches_completed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_dispatches_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'permissions': [('can_view_barcode_dispatch', 'Can view barcode dispatch sessions'), ('can_create_barcode_dispatch', 'Can create barcode dispatch sessions'), ('can_scan_barcode_dispatch', 'Can scan barcode dispatch labels'), ('can_complete_barcode_dispatch', 'Can mark barcode dispatch complete'), ('can_retry_barcode_dispatch_sap', 'Can retry barcode dispatch SAP sync')],
            },
        ),
        migrations.CreateModel(
            name='DispatchScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_barcode', models.TextField()),
                ('parsed_barcode', models.JSONField(blank=True, default=dict)),
                ('entity_type', models.CharField(choices=[('BOX', 'Box'), ('PALLET', 'Pallet'), ('SERIAL', 'Serial'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('entity_id', models.CharField(blank=True, default='', max_length=120)),
                ('material_code', models.CharField(blank=True, default='', max_length=80)),
                ('batch_number', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('uom', models.CharField(blank=True, default='', max_length=30)),
                ('result', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reject_code', models.CharField(blank=True, default='', max_length=80)),
                ('reject_message', models.TextField(blank=True, default='')),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_dispatch_scans', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='barcode.dispatchsession')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchSapSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=80)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_sync_logs', to='barcode.dispatchsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchSessionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField()),
                ('sap_line_no', models.CharField(max_length=80)),
                ('material_code', models.CharField(max_length=80)),
                ('material_description', models.TextField(blank=True, default='')),
                ('bill_qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('scanned_qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=30)),
                ('batch_number', models.CharField(blank=True, default='', max_length=120)),
                ('warehouse_code', models.CharField(blank=True, default='', max_length=40)),
                ('serial_required', models.BooleanField(default=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='barcode.dispatchsession')),
            ],
            options={
                'ordering': ['sequence_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchScannedUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_value', models.CharField(max_length=200)),
                ('entity_type', models.CharField(choices=[('BOX', 'Box'), ('PALLET', 'Pallet'), ('SERIAL', 'Serial'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('serial_number', models.CharField(blank=True, default='', max_length=120)),
                ('material_code', models.CharField(max_length=80)),
                ('batch_number', models.CharField(blank=True, default='', max_length=120)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_scanned_units', to='barcode.box')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_scanned_units', to='barcode.pallet')),
                ('scan_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_unit', to='barcode.dispatchscanlog')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_units', to='barcode.dispatchsession')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_units', to='barcode.dispatchsessionline')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='dispatchscanlog',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='barcode.dispatchsessionline'),
        ),
        migrations.AddIndex(
            model_name='dispatchsession',
            index=models.Index(fields=['company', 'bill_number'], name='barcode_dis_company_260f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchsession',
            index=models.Index(fields=['company', 'status', 'created_at'], name='barcode_dis_company_cbd908_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchsession',
            index=models.Index(fields=['company', 'sap_doc_entry'], name='barcode_dis_company_1c7815_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('company', 'bill_number'), name='unique_active_barcode_dispatch_bill'),
        ),
        migrations.AddIndex(
            model_name='dispatchsapsynclog',
            index=models.Index(fields=['session', 'operation', 'status'], name='barcode_dis_session_71d8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchsessionline',
            index=models.Index(fields=['session', 'sequence_no'], name='barcode_dis_session_810fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchsessionline',
            index=models.Index(fields=['session', 'status'], name='barcode_dis_session_bd6d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchsessionline',
            index=models.Index(fields=['material_code'], name='barcode_dis_materia_7c11cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsessionline',
            constraint=models.UniqueConstraint(fields=('session', 'sequence_no'), name='unique_dispatch_session_sequence'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsessionline',
            constraint=models.UniqueConstraint(fields=('session', 'sap_line_no'), name='unique_dispatch_session_sap_line'),
        ),
        migrations.AddConstraint(
            model_name='dispatchsessionline',
            constraint=models.CheckConstraint(condition=models.Q(('scanned_qty__lte', models.F('bill_qty'))), name='dispatch_line_scanned_lte_bill'),
        ),
        migrations.AddIndex(
            model_name='dispatchscannedunit',
            index=models.Index(fields=['session', 'line'], name='barcode_dis_session_74ca9d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchscannedunit',
            index=models.Index(fields=['barcode_value'], name='barcode_dis_barcode_c373f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispatchscannedunit',
            constraint=models.UniqueConstraint(fields=('session', 'barcode_value'), name='unique_dispatch_barcode_per_session'),
        ),
        migrations.AddConstraint(
            model_name='dispatchscannedunit',
            constraint=models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('session', 'serial_number'), name='unique_dispatch_serial_per_session'),
        ),
        migrations.AddIndex(
            model_name='dispatchscanlog',
            index=models.Index(fields=['session', 'scanned_at'], name='barcode_dis_session_5653a0_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchscanlog',
            index=models.Index(fields=['session', 'result'], name='barcode_dis_session_df589e_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchscanlog',
            index=models.Index(fields=['session', 'reject_code'], name='barcode_dis_session_33da89_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchscanlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='barcode_dis_entity__204f5f_idx'),
        ),
    ]
