# Generated by Django 6.0.1 on 2026-05-23 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_dispatch_statuses_and_totals(apps, schema_editor):
    DispatchSession = apps.get_model('barcode', 'DispatchSession')
    DispatchSessionLine = apps.get_model('barcode', 'DispatchSessionLine')
    status_map = {
        'IN_PROGRESS': 'PARTIAL',
        'SCANNING_COMPLETE': 'READY_TO_DISPATCH',
        'DISPATCHED': 'COMPLETED',
        'SAP_UPDATE_PENDING': 'COMPLETED',
        'SAP_UPDATE_FAILED': 'SAP_SYNC_FAILED',
    }
    for old_status, new_status in status_map.items():
        DispatchSession.objects.filter(status=old_status).update(status=new_status)

    for session in DispatchSession.objects.all().iterator():
        totals = DispatchSessionLine.objects.filter(session=session).aggregate(
            expected=models.Sum('bill_qty'),
            scanned=models.Sum('scanned_qty'),
        )
        session.total_expected_qty = totals['expected'] or 0
        session.total_scanned_qty = totals['scanned'] or 0
        if not session.delivery_number:
            session.delivery_number = session.reference_delivery_number
        session.save(update_fields=['status', 'total_expected_qty', 'total_scanned_qty', 'delivery_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('barcode', '0007_dispatchsession_dispatchscanlog_dispatchsapsynclog_and_more'),
        ('company', '0003_alter_usercompany_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=200)),
                ('barcode_type', models.CharField(choices=[('ITEM', 'Item'), ('BOX', 'Box'), ('PALLET', 'Pallet')], max_length=20)),
                ('material_code', models.CharField(blank=True, default='', max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('uom', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barcode Master',
                'verbose_name_plural': 'Barcode Master',
                'ordering': ['barcode'],
            },
        ),
        migrations.CreateModel(
            name='DispatchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_partial_dispatch', models.BooleanField(default=False)),
                ('allow_partial_pallet_dispatch', models.BooleanField(default=True)),
                ('allow_box_dispatch_from_pallet', models.BooleanField(default=True)),
                ('require_sequential_item_scanning', models.BooleanField(default=True)),
                ('require_sap_sync_on_completion', models.BooleanField(default=False)),
                ('allow_manual_close', models.BooleanField(default=True)),
                ('allow_admin_override', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispatch Settings',
                'verbose_name_plural': 'Dispatch Settings',
            },
        ),
        migrations.CreateModel(
            name='PalletBoxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('old_status', models.CharField(blank=True, default='', max_length=40)),
                ('new_status', models.CharField(blank=True, default='', max_length=40)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pallet Box History',
                'verbose_name_plural': 'Pallet Box History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='dispatchsession',
            options={'ordering': ['-updated_at', '-created_at'], 'permissions': [('can_view_barcode_dispatch', 'Can view barcode dispatch sessions'), ('can_create_barcode_dispatch', 'Can create barcode dispatch sessions'), ('can_scan_barcode_dispatch', 'Can scan barcode dispatch labels'), ('can_complete_barcode_dispatch', 'Can mark barcode dispatch complete'), ('can_close_barcode_dispatch', 'Can close barcode dispatch sessions'), ('can_retry_barcode_dispatch_sap', 'Can retry barcode dispatch SAP sync'), ('can_manage_barcode_dispatch_settings', 'Can manage barcode dispatch settings'), ('can_view_barcode_dispatch_reports', 'Can view barcode dispatch reports')]},
        ),
        migrations.RemoveConstraint(
            model_name='dispatchsession',
            name='unique_active_barcode_dispatch_bill',
        ),
        migrations.AddField(
            model_name='box',
            name='dispatch_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_boxes', to='barcode.dispatchsession'),
        ),
        migrations.AddField(
            model_name='box',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='removed_from_pallet_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='removed_from_pallet_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispatchsession',
            name='close_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispatchsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatchsession',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_dispatches_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchsession',
            name='delivery_number',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='dispatchsession',
            name='total_expected_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='dispatchsession',
            name='total_scanned_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pallet',
            name='available_boxes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='dispatch_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_pallets', to='barcode.dispatchsession'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='dispatched_boxes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pallet',
            name='total_boxes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('DISPATCHED', 'Dispatched'), ('DISMANTLED', 'Dismantled'), ('VOID', 'Void')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='boxmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('PALLETIZE', 'Palletize'), ('DEPALLETIZE', 'Depalletize'), ('DISPATCH', 'Dispatch'), ('REMOVE_FOR_DISPATCH', 'Remove for Dispatch'), ('DISMANTLE', 'Dismantle'), ('VOID', 'Void')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchscanlog',
            name='entity_type',
            field=models.CharField(choices=[('ITEM', 'Item'), ('BOX', 'Box'), ('PALLET', 'Pallet'), ('SERIAL', 'Serial'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchscannedunit',
            name='entity_type',
            field=models.CharField(choices=[('ITEM', 'Item'), ('BOX', 'Box'), ('PALLET', 'Pallet'), ('SERIAL', 'Serial'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dispatchscannedunit',
            name='scan_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_units', to='barcode.dispatchscanlog'),
        ),
        migrations.AlterField(
            model_name='dispatchsession',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('READY_TO_DISPATCH', 'Ready to Dispatch'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('SAP_SYNC_FAILED', 'SAP Sync Failed')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PARTIAL', 'Partial'), ('DISPATCHED', 'Dispatched'), ('EMPTY', 'Empty'), ('INACTIVE', 'Inactive'), ('CLEARED', 'Cleared'), ('SPLIT', 'Split'), ('VOID', 'Void')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='palletmovement',
            name='movement_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('DISPATCH', 'Dispatch'), ('REMOVE_FOR_DISPATCH', 'Remove for Dispatch'), ('DISMANTLE', 'Dismantle'), ('CLEAR', 'Clear'), ('SPLIT', 'Split'), ('VOID', 'Void')], max_length=20),
        ),
        migrations.RunPython(migrate_dispatch_statuses_and_totals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='dispatchsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'ACTIVE', 'PARTIAL', 'READY_TO_DISPATCH', 'COMPLETED', 'SAP_SYNC_FAILED'])), fields=('company', 'bill_number'), name='unique_active_barcode_dispatch_bill'),
        ),
        migrations.AddField(
            model_name='barcodemaster',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_master_records', to='barcode.box'),
        ),
        migrations.AddField(
            model_name='barcodemaster',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='barcode_master_records', to='company.company'),
        ),
        migrations.AddField(
            model_name='barcodemaster',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_master_records', to='barcode.pallet'),
        ),
        migrations.AddField(
            model_name='dispatchsettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode_dispatch_settings', to='company.company'),
        ),
        migrations.AddField(
            model_name='palletboxhistory',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_history', to='barcode.box'),
        ),
        migrations.AddField(
            model_name='palletboxhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_box_history', to='company.company'),
        ),
        migrations.AddField(
            model_name='palletboxhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallet_box_history_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='palletboxhistory',
            name='dispatch_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallet_box_history', to='barcode.dispatchsession'),
        ),
        migrations.AddField(
            model_name='palletboxhistory',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_history', to='barcode.pallet'),
        ),
        migrations.AddIndex(
            model_name='barcodemaster',
            index=models.Index(fields=['company', 'barcode_type', 'is_active'], name='barcode_bar_company_01ede9_idx'),
        ),
        migrations.AddIndex(
            model_name='barcodemaster',
            index=models.Index(fields=['material_code'], name='barcode_bar_materia_787486_idx'),
        ),
        migrations.AddConstraint(
            model_name='barcodemaster',
            constraint=models.UniqueConstraint(fields=('company', 'barcode'), name='unique_barcode_master_per_company'),
        ),
        migrations.AddIndex(
            model_name='palletboxhistory',
            index=models.Index(fields=['pallet', 'box', 'created_at'], name='barcode_pal_pallet__73dea2_idx'),
        ),
        migrations.AddIndex(
            model_name='palletboxhistory',
            index=models.Index(fields=['dispatch_session', 'created_at'], name='barcode_pal_dispatc_7f6e9f_idx'),
        ),
        migrations.AddIndex(
            model_name='palletboxhistory',
            index=models.Index(fields=['action'], name='barcode_pal_action_89ba48_idx'),
        ),
    ]
