# Generated by Django 6.0.1 on 2026-05-06 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0007_alter_vehicleentry_entry_type'),
        ('gate_core', '0007_emptyvehiclegateout'),
        ('vehicle_management', '0006_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyVehicleGateIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('BST', 'BST'), ('DISPATCH', 'Dispatch'), ('REPAIR_MOVEMENT', 'Repair Movement'), ('JOB_WORK', 'Job Work'), ('OTHER', 'Other')], max_length=30)),
                ('gate_in_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('security_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empty_vehicle_gate_ins', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empty_vehicle_gate_ins', to='driver_management.driver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empty_vehicle_gate_ins', to='vehicle_management.vehicle')),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empty_vehicle_gate_in', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-gate_in_date', '-in_time', '-created_at'],
                'indexes': [models.Index(fields=['company', 'gate_in_date'], name='gate_core_e_company_4cdce4_idx'), models.Index(fields=['reason'], name='gate_core_e_reason_d294fb_idx'), models.Index(fields=['vehicle'], name='gate_core_e_vehicle_93ffc8_idx')],
            },
        ),
    ]
