# Generated by Django 6.0.3 on 2026-05-06 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0007_alter_vehicleentry_entry_type'),
        ('gate_core', '0008_emptyvehiclegatein'),
        ('vehicle_management', '0006_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSTGateOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.CharField(max_length=50)),
                ('sap_doc_date', models.DateField(blank=True, null=True)),
                ('sap_from_warehouse', models.CharField(blank=True, max_length=50)),
                ('sap_to_warehouse', models.CharField(blank=True, max_length=50)),
                ('sap_reference', models.CharField(blank=True, max_length=100)),
                ('sap_comments', models.TextField(blank=True)),
                ('gate_out_date', models.DateField()),
                ('out_time', models.TimeField()),
                ('security_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_outs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_outs', to='driver_management.driver')),
                ('empty_vehicle_gate_in', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_out', to='gate_core.emptyvehiclegatein')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_outs', to='vehicle_management.vehicle')),
                ('vehicle_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_out', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-gate_out_date', '-out_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BSTGateOutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_num', models.IntegerField()),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('from_warehouse', models.CharField(blank=True, max_length=50)),
                ('to_warehouse', models.CharField(blank=True, max_length=50)),
                ('bst_gate_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate_core.bstgateout')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['line_num'],
            },
        ),
        migrations.AddIndex(
            model_name='bstgateout',
            index=models.Index(fields=['company', 'gate_out_date'], name='gate_core_b_company_98d00f_idx'),
        ),
        migrations.AddIndex(
            model_name='bstgateout',
            index=models.Index(fields=['status'], name='gate_core_b_status_db266c_idx'),
        ),
        migrations.AddIndex(
            model_name='bstgateout',
            index=models.Index(fields=['sap_doc_entry'], name='gate_core_b_sap_doc_196603_idx'),
        ),
        migrations.AddIndex(
            model_name='bstgateout',
            index=models.Index(fields=['sap_doc_num'], name='gate_core_b_sap_doc_6040fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='bstgateout',
            constraint=models.UniqueConstraint(fields=('company', 'sap_doc_entry'), name='unique_bst_gate_out_sap_doc_per_company'),
        ),
        migrations.AddConstraint(
            model_name='bstgateoutitem',
            constraint=models.UniqueConstraint(fields=('bst_gate_out', 'line_num'), name='unique_bst_gate_out_line'),
        ),
    ]
