# Generated by Django 6.0.3 on 2026-05-06 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0007_alter_vehicleentry_entry_type'),
        ('gate_core', '0009_bstgateout_bstgateoutitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bstgateout',
            name='unique_bst_gate_out_sap_doc_per_company',
        ),
        migrations.AddField(
            model_name='bstgateout',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bstgateout',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bstgateout',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bst_gate_outs_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bstgateout',
            name='empty_vehicle_gate_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_outs', to='gate_core.emptyvehiclegatein'),
        ),
        migrations.AlterField(
            model_name='bstgateout',
            name='vehicle_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_outs', to='driver_management.vehicleentry'),
        ),
    ]
