# Generated by Django 6.0.3 on 2026-05-06 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0008_alter_vehicleentry_entry_type'),
        ('gate_core', '0010_remove_bstgateout_unique_bst_gate_out_sap_doc_per_company_and_more'),
        ('vehicle_management', '0006_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BSTGateIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('gate_in_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('security_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('bst_gate_out', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_ins', to='gate_core.bstgateout')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_ins', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_ins', to='driver_management.driver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_ins', to='vehicle_management.vehicle')),
                ('vehicle_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_ins', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-gate_in_date', '-in_time', '-created_at'],
                'indexes': [models.Index(fields=['company', 'gate_in_date'], name='gate_core_b_company_c7401c_idx'), models.Index(fields=['status'], name='gate_core_b_status_41cf42_idx'), models.Index(fields=['vehicle'], name='gate_core_b_vehicle_f6df4f_idx'), models.Index(fields=['bst_gate_out'], name='gate_core_b_bst_gat_99b5b3_idx')],
            },
        ),
    ]
