# Generated by Django 6.0.3 on 2026-05-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0010_alter_vehicleentry_entry_type'),
        ('gate_core', '0012_bstgatereturn'),
        ('vehicle_management', '0006_alter_vehicle_vehicle_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkGateIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.CharField(max_length=50)),
                ('sap_doc_date', models.DateField(blank=True, null=True)),
                ('sap_supplier_code', models.CharField(blank=True, max_length=50)),
                ('sap_supplier_name', models.CharField(blank=True, max_length=255)),
                ('sap_reference', models.CharField(blank=True, max_length=100)),
                ('sap_comments', models.TextField(blank=True)),
                ('sap_branch_id', models.IntegerField(blank=True, null=True)),
                ('gate_in_date', models.DateField()),
                ('in_time', models.TimeField()),
                ('security_name', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_gate_ins', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_gate_ins', to='driver_management.driver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_gate_ins', to='vehicle_management.vehicle')),
                ('vehicle_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_work_gate_ins', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-gate_in_date', '-in_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkGateInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_num', models.IntegerField()),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('warehouse_code', models.CharField(blank=True, max_length=50)),
                ('base_type', models.IntegerField(blank=True, null=True)),
                ('base_entry', models.IntegerField(blank=True, null=True)),
                ('base_line', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('job_work_gate_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate_core.jobworkgatein')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['line_num'],
            },
        ),
        migrations.AddIndex(
            model_name='jobworkgatein',
            index=models.Index(fields=['company', 'gate_in_date'], name='gate_core_j_company_5e9b99_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkgatein',
            index=models.Index(fields=['status'], name='gate_core_j_status_dce790_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkgatein',
            index=models.Index(fields=['vehicle'], name='gate_core_j_vehicle_a5d6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkgatein',
            index=models.Index(fields=['sap_doc_entry'], name='gate_core_j_sap_doc_983b27_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkgatein',
            index=models.Index(fields=['sap_doc_num'], name='gate_core_j_sap_doc_aad48f_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobworkgateinitem',
            constraint=models.UniqueConstraint(fields=('job_work_gate_in', 'line_num'), name='unique_job_work_gate_in_line'),
        ),
    ]
