# Generated by Django 6.0.3 on 2026-05-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0013_jobworkgatein_jobworkgateinitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobworkgatein',
            name='sap_doc_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
