# Generated by Django 6.0.3 on 2026-05-07 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0010_alter_vehicleentry_entry_type'),
        ('gate_core', '0014_jobworkgatein_sap_doc_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emptyvehiclegateout',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emptyvehiclegateout',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emptyvehiclegateout',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empty_vehicle_gate_outs_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emptyvehiclegateout',
            name='vehicle_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empty_vehicle_gate_out', to='driver_management.vehicleentry'),
        ),
    ]
