# Generated by Django 6.0.1 on 2026-05-08 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def copy_existing_bst_out_quantity_to_actual(apps, schema_editor):
    BSTGateOutItem = apps.get_model('gate_core', 'BSTGateOutItem')
    BSTGateOutItem.objects.update(actual_quantity=F('quantity'))


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0016_emptyvehiclegatein_bst_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bstgateoutitem',
            name='actual_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.RunPython(copy_existing_bst_out_quantity_to_actual, migrations.RunPython.noop),
        migrations.CreateModel(
            name='BSTGateInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_num', models.IntegerField()),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('actual_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('receiving_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('from_warehouse', models.CharField(blank=True, max_length=50)),
                ('to_warehouse', models.CharField(blank=True, max_length=50)),
                ('bst_gate_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate_core.bstgatein')),
                ('bst_gate_out_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_in_items', to='gate_core.bstgateoutitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['line_num'],
                'constraints': [models.UniqueConstraint(fields=('bst_gate_in', 'line_num'), name='unique_bst_gate_in_line')],
            },
        ),
        migrations.CreateModel(
            name='EmptyVehicleGateInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_num', models.IntegerField()),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('sap_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('actual_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('from_warehouse', models.CharField(blank=True, max_length=50)),
                ('to_warehouse', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('empty_vehicle_gate_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate_core.emptyvehiclegatein')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['line_num'],
                'constraints': [models.UniqueConstraint(fields=('empty_vehicle_gate_in', 'line_num'), name='unique_empty_vehicle_gate_in_line')],
            },
        ),
    ]
