# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0017_bstgateoutitem_actual_quantity_bstgateinitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobworkgatein',
            name='sap_doc_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobworkgatein',
            name='sap_doc_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_order_doc_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_order_doc_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_item_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_planned_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_completed_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_rejected_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_remaining_qty',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_warehouse',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='jobworkgatein',
            name='production_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobworkgatein',
            index=models.Index(fields=['production_order_doc_entry'], name='gate_core_j_product_2438c2_idx'),
        ),
        migrations.AddIndex(
            model_name='jobworkgatein',
            index=models.Index(fields=['production_order_doc_num'], name='gate_core_j_product_e6ae9d_idx'),
        ),
    ]
