# Generated by Django 6.0.3 on 2026-05-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gate_core', '0019_rejected_qc_return_weighment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedqcreturnentry',
            name='gatepass_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
