# Generated by Django 6.0.3 on 2026-05-09 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('dispatch_plans', '0004_rename_dispatch_pl_company_d4f18f_idx_dispatch_pl_company_4e52c8_idx'),
        ('driver_management', '0010_alter_vehicleentry_entry_type'),
        ('gate_core', '0020_rejectedqcreturnentry_gatepass_documents'),
        ('vehicle_management', '0007_transporter_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchGateLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_gate_locks_changed', to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_gate_lock', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchGateOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_no', models.CharField(max_length=50, unique=True)),
                ('sap_invoice_doc_entry', models.IntegerField()),
                ('sap_invoice_doc_num', models.CharField(blank=True, max_length=30)),
                ('customer_code', models.CharField(blank=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('ship_to_address', models.TextField(blank=True)),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sap_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('gate_out_date', models.DateField()),
                ('out_time', models.TimeField()),
                ('security_name', models.CharField(blank=True, max_length=100)),
                ('seal_no', models.CharField(blank=True, max_length=100)),
                ('pgi_document_no', models.CharField(blank=True, max_length=100)),
                ('goods_issue_posted', models.BooleanField(default=False)),
                ('invoice_checked', models.BooleanField(default=False)),
                ('delivery_note_checked', models.BooleanField(default=False)),
                ('eway_bill_checked', models.BooleanField(default=False)),
                ('lr_checked', models.BooleanField(default=False)),
                ('physical_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('physical_uom', models.CharField(blank=True, choices=[('PCS', 'Pcs'), ('BOX', 'Box')], max_length=10)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, editable=False, max_digits=18, null=True)),
                ('weighbridge_slip_no', models.CharField(blank=True, max_length=50)),
                ('first_weighment_time', models.DateTimeField(blank=True, null=True)),
                ('second_weighment_time', models.DateTimeField(blank=True, null=True)),
                ('dock_photo', models.FileField(blank=True, null=True, upload_to='dispatch_gate/dock_photos/')),
                ('gatepass_document', models.FileField(blank=True, null=True, upload_to='dispatch_gate/gatepass_documents/')),
                ('attachment_notes', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('gatepass_no', models.CharField(blank=True, max_length=50)),
                ('gatepass_code', models.CharField(blank=True, max_length=20)),
                ('gate_printed', models.BooleanField(default=False)),
                ('print_commit', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='IN_PROGRESS', max_length=20)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_gate_outs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gate_outs', to='dispatch_plans.dispatchplan')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_gate_outs', to='driver_management.driver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_gate_outs', to='vehicle_management.vehicle')),
                ('vehicle_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_gate_outs', to='driver_management.vehicleentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchGateOutLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_num', models.IntegerField(default=0)),
                ('item_code', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=255)),
                ('order_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('dispatched_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('uom', models.CharField(blank=True, max_length=30)),
                ('warehouse', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate_core.dispatchgateout')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['line_num', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatchgateout',
            index=models.Index(fields=['company', 'gate_out_date'], name='gate_core_d_company_4e7f54_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchgateout',
            index=models.Index(fields=['company', 'sap_invoice_doc_entry'], name='gate_core_d_company_4369e9_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchgateout',
            index=models.Index(fields=['company', 'status'], name='gate_core_d_company_865564_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchgateout',
            index=models.Index(fields=['company', 'gate_printed', 'print_commit'], name='gate_core_d_company_407fa8_idx'),
        ),
    ]
