# Generated by Django 6.0.3 on 2026-05-20 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_child_documents(apps, schema_editor):
    SalesDispatchGateOut = apps.get_model("gate_core", "SalesDispatchGateOut")
    SalesDispatchGateOutDocument = apps.get_model(
        "gate_core",
        "SalesDispatchGateOutDocument",
    )
    SalesDispatchGateOutItem = apps.get_model("gate_core", "SalesDispatchGateOutItem")

    for entry in SalesDispatchGateOut.objects.all().iterator():
        document, _ = SalesDispatchGateOutDocument.objects.get_or_create(
            sales_dispatch_id=entry.id,
            document_type=entry.document_type,
            sap_doc_entry=entry.sap_doc_entry,
            defaults={
                "company_id": entry.company_id,
                "dispatch_plan_id": entry.dispatch_plan_id,
                "sap_doc_num": entry.sap_doc_num,
                "sap_doc_date": entry.sap_doc_date,
                "sap_doc_total": entry.sap_doc_total,
                "sap_branch_id": entry.sap_branch_id,
                "sap_branch_name": entry.sap_branch_name,
                "sap_reference": entry.sap_reference,
                "sap_comments": entry.sap_comments,
                "customer_code": entry.customer_code,
                "customer_name": entry.customer_name,
                "ship_to_code": entry.ship_to_code,
                "ship_to_address": entry.ship_to_address,
                "place_of_supply": entry.place_of_supply,
                "bp_gstin": entry.bp_gstin,
                "eway_bill": entry.eway_bill,
                "from_warehouse": entry.from_warehouse,
                "to_warehouse": entry.to_warehouse,
                "warehouses": entry.warehouses,
                "item_summary": entry.item_summary,
                "base_refs": entry.base_refs,
                "total_quantity": entry.total_quantity,
                "total_litres": entry.total_litres,
                "total_boxes": entry.total_boxes,
                "total_weight": entry.total_weight,
                "created_by_id": entry.created_by_id,
                "updated_by_id": entry.updated_by_id,
                "is_active": entry.is_active,
            },
        )
        SalesDispatchGateOutItem.objects.filter(
            sales_dispatch_id=entry.id,
            document__isnull=True,
        ).update(document_id=document.id)


def remove_child_documents(apps, schema_editor):
    SalesDispatchGateOutDocument = apps.get_model(
        "gate_core",
        "SalesDispatchGateOutDocument",
    )
    SalesDispatchGateOutItem = apps.get_model("gate_core", "SalesDispatchGateOutItem")
    SalesDispatchGateOutItem.objects.update(document_id=None)
    SalesDispatchGateOutDocument.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('dispatch_plans', '0009_dispatchplan_service_grpo_defaults'),
        ('gate_core', '0024_salesdispatchlock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDispatchGateOutDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('INVOICE', 'A/R Invoice'), ('STOCK_TRANSFER', 'Stock Transfer')], max_length=30)),
                ('sap_doc_entry', models.IntegerField()),
                ('sap_doc_num', models.CharField(blank=True, max_length=50)),
                ('sap_doc_date', models.DateField(blank=True, null=True)),
                ('sap_doc_total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sap_branch_id', models.IntegerField(blank=True, null=True)),
                ('sap_branch_name', models.CharField(blank=True, max_length=150)),
                ('sap_reference', models.CharField(blank=True, max_length=150)),
                ('sap_comments', models.TextField(blank=True)),
                ('customer_code', models.CharField(blank=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('ship_to_code', models.CharField(blank=True, max_length=100)),
                ('ship_to_address', models.TextField(blank=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=150)),
                ('bp_gstin', models.CharField(blank=True, max_length=30)),
                ('eway_bill', models.CharField(blank=True, max_length=100)),
                ('from_warehouse', models.CharField(blank=True, max_length=50)),
                ('to_warehouse', models.CharField(blank=True, max_length=50)),
                ('warehouses', models.TextField(blank=True)),
                ('item_summary', models.TextField(blank=True)),
                ('base_refs', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total_litres', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total_boxes', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_dispatch_gate_out_documents', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('dispatch_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_dispatch_gate_out_documents', to='dispatch_plans.dispatchplan')),
                ('sales_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gate_core.salesdispatchgateout')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='salesdispatchgateoutitem',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gate_core.salesdispatchgateoutdocument'),
        ),
        migrations.RunPython(create_child_documents, remove_child_documents),
        migrations.AddIndex(
            model_name='salesdispatchgateoutitem',
            index=models.Index(fields=['sales_dispatch', 'document', 'line_num'], name='gate_core_s_sales_d_172951_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatchgateoutdocument',
            index=models.Index(fields=['company', 'document_type', 'sap_doc_entry'], name='gate_core_s_company_5cb293_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatchgateoutdocument',
            index=models.Index(fields=['sales_dispatch', 'document_type'], name='gate_core_s_sales_d_047197_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatchgateoutdocument',
            index=models.Index(fields=['sap_doc_num'], name='gate_core_s_sap_doc_e64a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesdispatchgateoutdocument',
            index=models.Index(fields=['customer_name'], name='gate_core_s_custome_15511a_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesdispatchgateoutdocument',
            constraint=models.UniqueConstraint(fields=('sales_dispatch', 'document_type', 'sap_doc_entry'), name='unique_sales_dispatch_child_document'),
        ),
    ]
