# Generated by Django 6.0.1 on 2026-05-21 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_existing_original_prints(apps, schema_editor):
    SalesDispatchGateOut = apps.get_model("gate_core", "SalesDispatchGateOut")
    SalesDispatchGatepassPrintLog = apps.get_model(
        "gate_core",
        "SalesDispatchGatepassPrintLog",
    )

    logs = []
    printed_entries = (
        SalesDispatchGateOut.objects
        .filter(gatepass_no__isnull=False)
        .exclude(gatepass_no="")
        .iterator()
    )
    for entry in printed_entries:
        printed_at = entry.printed_at or entry.updated_at or entry.created_at
        logs.append(
            SalesDispatchGatepassPrintLog(
                company_id=entry.company_id,
                sales_dispatch_id=entry.id,
                gatepass_no=entry.gatepass_no,
                entry_status=entry.status,
                copy_number=1,
                print_type="ORIGINAL",
                printed_by_id=entry.printed_by_id,
                printed_at=printed_at,
                created_at=printed_at,
                updated_at=printed_at,
                created_by_id=entry.printed_by_id or entry.updated_by_id or entry.created_by_id,
                updated_by_id=entry.updated_by_id or entry.printed_by_id or entry.created_by_id,
                user_agent="Migrated from SalesDispatchGateOut print fields",
            )
        )

    if logs:
        SalesDispatchGatepassPrintLog.objects.bulk_create(logs, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('gate_core', '0025_salesdispatchgateoutdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDispatchGatepassPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gatepass_no', models.CharField(max_length=80)),
                ('entry_status', models.CharField(blank=True, max_length=30)),
                ('copy_number', models.PositiveIntegerField(default=1)),
                ('print_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('REPRINT', 'Reprint')], default='ORIGINAL', max_length=20)),
                ('reprint_reason', models.TextField(blank=True, default='')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('printer_name', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_dispatch_gatepass_print_logs', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_dispatch_gatepass_print_logs', to=settings.AUTH_USER_MODEL)),
                ('sales_dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatepass_print_logs', to='gate_core.salesdispatchgateout')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-printed_at', '-id'],
                'indexes': [models.Index(fields=['company', 'print_type', 'printed_at'], name='gate_core_s_company_18baa3_idx'), models.Index(fields=['sales_dispatch', 'print_type'], name='gate_core_s_sales_d_481298_idx'), models.Index(fields=['gatepass_no'], name='gate_core_s_gatepas_70d89e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('print_type', 'ORIGINAL')), fields=('sales_dispatch',), name='unique_original_sales_dispatch_gatepass_print'), models.UniqueConstraint(fields=('sales_dispatch', 'copy_number'), name='unique_sales_dispatch_gatepass_copy_number')],
            },
        ),
        migrations.RunPython(seed_existing_original_prints, migrations.RunPython.noop),
    ]
