# Generated by Django 6.0.3 on 2026-05-25 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_usercompany_role'),
        ('driver_management', '0011_alter_vehicleentry_entry_type'),
        ('gate_core', '0027_sales_dispatch_edit_reprint_permissions'),
        ('vehicle_management', '0007_transporter_gstin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bstgatein',
            name='sales_dispatch_gate_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_ins', to='gate_core.salesdispatchgateout'),
        ),
        migrations.AddField(
            model_name='bstgateinitem',
            name='sales_dispatch_gate_out_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_in_items', to='gate_core.salesdispatchgateoutitem'),
        ),
        migrations.AlterField(
            model_name='bstgatein',
            name='bst_gate_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_ins', to='gate_core.bstgateout'),
        ),
        migrations.AlterField(
            model_name='bstgateinitem',
            name='bst_gate_out_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bst_gate_in_items', to='gate_core.bstgateoutitem'),
        ),
        migrations.AddIndex(
            model_name='bstgatein',
            index=models.Index(fields=['sales_dispatch_gate_out'], name='gate_core_b_sales_d_70ba1e_idx'),
        ),
    ]
