# Generated by Codex on 2026-05-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("barcode", "0005_barcodesequence"),
        ("company", "0003_alter_usercompany_role"),
        ("gate_core", "0028_bstgatein_sales_dispatch_gate_out_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesDispatchBoxScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("box_barcode", models.CharField(max_length=100)),
                ("barcode_raw", models.CharField(blank=True, max_length=500)),
                ("item_code", models.CharField(blank=True, max_length=100)),
                ("item_name", models.CharField(blank=True, max_length=255)),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("uom", models.CharField(blank=True, max_length=20)),
                ("box_status", models.CharField(blank=True, max_length=20)),
                ("warehouse_code", models.CharField(blank=True, max_length=50)),
                ("pallet_code", models.CharField(blank=True, max_length=100)),
                ("scanned_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_dispatch_scans",
                        to="barcode.box",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_dispatch_box_scans",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="box_scans",
                        to="gate_core.salesdispatchgateout",
                    ),
                ),
                (
                    "scan_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_dispatch_box_scans",
                        to="barcode.scanlog",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_dispatch_box_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="salesdispatchboxscan",
            index=models.Index(
                fields=["company", "sales_dispatch"],
                name="gate_core_s_company_855151_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="salesdispatchboxscan",
            index=models.Index(fields=["box_barcode"], name="gate_core_s_box_bar_ac68b8_idx"),
        ),
        migrations.AddIndex(
            model_name="salesdispatchboxscan",
            index=models.Index(fields=["scanned_at"], name="gate_core_s_scanned_b69867_idx"),
        ),
        migrations.AddConstraint(
            model_name="salesdispatchboxscan",
            constraint=models.UniqueConstraint(
                fields=("sales_dispatch", "box_barcode"),
                name="unique_sales_dispatch_box_scan",
            ),
        ),
    ]
